config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks
  get 'tasks/:id/confirm_destroy', to: 'tasks#confirm_destroy', as: 'confirm_destroy_task'
  get 'tasks/:id/contenu', to: 'tasks#contenu', as: 'contenu_task'
  root 'tasks#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:edit,:contenu, :update, :destroy, :confirm_destroy]
  
    def index
      @tasks = Task.all
    end
  
    def new
      @task = Task.new
    end
  
    def create
      @task = Task.new(task_params)
      if @task.save
        redirect_to tasks_path, notice: 'La tâche a été mise à jour avec succès.'
      else
        render :new
      end
    end
  
    def edit
    end
    
    def contenu
    end
  
    def update
      if @task.update(task_params)
        redirect_to tasks_path, notice: 'La tâche a été mise à jour avec succès.'
      else
        render :edit
      end
    end
  
    def destroy
      @task.destroy
      redirect_to tasks_path, notice: 'La tâche a été supprimée avec succès.'
    end
  
    def confirm_destroy
    end
  
    private
  
    def set_task
      @task = Task.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:title, :description,:dayforexecution)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmanager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main >
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/confirm_destroy.html.erb
<a href="/"><h1 class="text-yellow-500 px-[10px] items-center bg-gray-950 text-center font-bold w-full text-[50px]">Confirmation de suppression</h1></a><br>

<p class="text-black-600 text-[3vw] text-center font-bold">Voulez-vous vraiment supprimer cette tâche ?</p>

<p class="text-red-600 text-[1.5vw] text-center font-bold"><strong>Titre :</strong> <%= @task.title %></p>
<p class="text-red-600 text-[1.5vw] text-center font-bold"><strong>Description :</strong> <%= @task.description %></p>
<p class="text-red-600 text-[1.5vw] text-center font-bold"><strong>Jour d'execution :</strong> <%= @task.dayforexecution %></p>


<div class="text-center pt-[2vh] my-[2vh]">
    <%= button_to 'Confirmer la suppression', task_path(@task), method: :delete, class: "bg-green-500 mb-[2vh] items-center cursor-pointer hover:text-white text-xl rounded p-2 font-bold"  %>
    <%= link_to 'Annuler', tasks_path,  class: "cursor-pointer hover:text-white bg-red-500 text-xl rounded p-2 font-bold"  %>
</div>

app/views/tasks/contenu.html.erb
<a href="/"><h1 class="text-yellow-500 px-[10px] items-center bg-gray-950 text-center font-bold w-full text-[50px]">Contenu de la tâche</h1></a><br>


<p class="text-red-600 text-[1.5vw] text-center font-bold"><strong>Jour d'execution :</strong> <%= @task.dayforexecution %></p><br><br>
<div class="text-center">
  <%= link_to 'Retour', tasks_path, class:"text-center hover:bg-gray-900 hover:rounded w-[10%] mt-[2vw] p-2  text-xl font-bold text-yellow-600"%>
</div>

app/views/tasks/copier.html.erb
<a href="/"><h1 class="text-yellow-500 px-[10px] items-center bg-gray-950 text-center font-bold w-full text-[50px]">Nouvelle tâche</h1></a><br>

<div class="bg-gray-400 text-center h-[40vh]">
  <%= form_with(model: @task, local: true) do |form| %>
    &nbsp;&nbsp;
    <div class="text-xl font-bold">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= form.label :title%>
      <%= form.text_field :title %>
    </div>

    <br>

    <div class="text-xl font-bold">
      <%= form.label :description, class:"top-[14vw] right-[60vw] absolute text-red-500"%>
      <%= form.text_area :description, class:"w-[18.5vw]" %>
    </div>

    <%= form.submit class: "cursor-pointer hover:bg-gray-500 text-xl hover:rounded p-2 font-bold" %>
  
  <% end %>
  <%= link_to 'Retour', tasks_path, class:"text-center hover:bg-gray-900 hover:rounded w-[10%] mt-[2vw] p-2  text-xl font-bold text-red-600"%>
  
</div>










<%= form_with(model: @task, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Retour', tasks_path %>

app/views/tasks/edit.html.erb
<a href="/"><h1 class="text-yellow-500 px-[10px] items-center bg-gray-950 text-center font-bold w-full text-[50px]">Modifier la tâche</h1></a><br>

<div class="bg-gray-400 text-center h-[40vh]">
  <%= form_with(model: @task, local: true) do |form| %>
    &nbsp;&nbsp;
    <div class="text-xl font-bold">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= form.label :title%>
      <%= form.text_field :title %>
    </div>

    <br>

    <div class="text-xl font-bold">
      <%= form.label :description, class:"top-[14vw] right-[60vw] absolute text-red-500"%>
      <%= form.text_area :description, class:"w-[18.5vw]" %>
    </div>


    <div class="text-xl font-bold">
      <%= form.label :dayforexecution,"Jour d'execution" ,class:"top-[14vw] right-[60vw]"%>
      <%= form.text_field :dayforexecution %>
    </div>

    <%= form.submit "Modifier la tâche",class: "cursor-pointer hover:bg-gray-500 text-xl hover:rounded p-2 font-bold" %>
  
  <% end %>
  <%= link_to 'Retour', tasks_path, class:"text-center hover:bg-gray-900 hover:rounded w-[10%] mt-[2vw] p-2  text-xl font-bold text-red-600"%>
  
</div>

app/views/tasks/index.html.erb
<div class="bg-gray-400">
  <nav class="text-red-500 px-[10px] items-center bg-gray-950 text-center font-bold w-full text-[50px]">
    L.I.S.T.E&nbsp; &nbsp; D.E.S &nbsp; &nbsp;T.A.C.H.E.S
  </nav>

  <table class="border-solid border-1 border-black mt-[40px] text-yellow-500 px-[40px] items-center bg-gray-400 text-center font-bold w-full text-[25px]">
    <tr>
      <th class="border-solid border-2 border-black text-black">Titre</th>
      <th class="border-solid border-2 border-black text-black">Description</th>
      <th class="border-solid border-2 border-black text-black" colspan="3">Options</th>
    </tr>

    <% @tasks.each do |task| %>
      <tr>
        <td class="border-solid border-2 border-black"><%= task.title %></td>
        <td class="border-solid border-2 border-black"><%= task.description %></td>
        <td class="border-solid border-2 border-black hover:bg-gray-900 text-blue-600"><%= link_to 'Modifier', edit_task_path(task) %></td>
        <td class="border-solid border-2 border-black hover:bg-gray-900 text-red-600"><%= link_to 'Supprimer', confirm_destroy_task_path(task) %></td>
        <td class="border-solid border-2 border-black hover:bg-gray-900 text-green-600"><%= link_to 'Voir le contenu', contenu_task_path(task) %></td>
      </tr>
    <% end %>
  </table>
  <% if flash[:notice] %>
    <div class="notice text-center font-bold text-[50px] text-blue-600"> <%=flash[:notice] %> </div>
  <%end%>

  <p class="text-white rounded hover:bg-white hover:text-green-700 mt-[2.5vw] text-center items-center content-center ml-[40%] mr-[40%] bg-green-900 w-[20%] font-bold text-[25px] "><%= link_to 'Nouvelle tâche', new_task_path %></p><br>

</div>

app/views/tasks/new.html.erb
<a href="/"><h1 class="text-yellow-500 px-[10px] items-center bg-gray-950 text-center font-bold w-full text-[50px]">Nouvelle tâche</h1></a><br>

<div class="bg-gray-400 text-center h-[40vh]">
  <%= form_with(model: @task, local: true) do |form| %>
    &nbsp;&nbsp;
    <div class="text-xl font-bold">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= form.label :title%>
      <%= form.text_field :title %>
    </div>

    <br>

    <div class="text-xl font-bold">
      <%= form.label :description, class:"top-[14vw] right-[60vw] absolute"%>
      <%= form.text_area :description, class:"relative" %>
    </div>


    <div class="text-xl font-bold">
      <%= form.label :dayforexecution,"Jour d'execution" ,class:"top-[14vw] right-[60vw]"%>
      <%= form.text_field :dayforexecution %>
    </div>

    <%= form.submit "Créer une nouvelle tâche", class: "cursor-pointer hover:bg-gray-500 text-xl hover:rounded p-2 font-bold" %>
  
  <% end %>
  <%= link_to 'Retour', tasks_path, class:"text-center hover:bg-gray-900 hover:rounded w-[10%] mt-[2vw] p-2  text-xl font-bold text-red-600"%>
  
</div>